networks:
  available-spots-finder_default:
    external: true
    name: "available-spots-finder_default"

services:

  available-spots-finder_bot_1:
    command:
      - "uv"
      - "run"
      - "python3"
      - "bot.py"
    container_name: "available-spots-finder_bot_1"
    environment:
      - "TELEGRAM_BOT_TOKEN=8712860446:AAF0mFzc4dS0hIAA7XBUWnCLcHox0fSrMRg"
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=7169605F62C751356D054A26A821E680E5FA6305"
      - "PYTHON_VERSION=3.12.12"
      - "PYTHON_SHA256=fb85a13414b028c49ba18bbd523c2d055a30b56b18b92ce454ea2c51edc656c4"
    hostname: "cd24398390df"
    image: "available-spots-finder_bot"
    ipc: "private"
    labels:
      com.docker.compose.config-hash: "bf0d28c1af36b9a6aa4d36c3e712a398c4d12b566d8e392c5ac8c84f424467d1"
      com.docker.compose.container-number: "1"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "available-spots-finder"
      com.docker.compose.project.config_files: "docker-compose.yml"
      com.docker.compose.project.working_dir: "/home/ran-markovich/Projects/available-spots-finder"
      com.docker.compose.service: "bot"
      com.docker.compose.version: "1.29.2"
    logging:
      driver: "json-file"
      options: {}
    networks:
      - "available-spots-finder_default"
    restart: "unless-stopped"
    working_dir: "/app"

  n8n:

    container_name: "n8n"

    entrypoint:
      - "tini"
      - "--"
      - "/docker-entrypoint.sh"

    environment:
      - "N8N_HOST=n8n.ranmarkovich.com"
      - "N8N_PROTOCOL=https"
      - "WEBHOOK_URL=https://n8n.ranmarkovich.com/"
      - "N8N_EDITOR_BASE_URL=https://n8n.ranmarkovich.com/"
      - "NODE_VERSION=24.13.1"
      - "NPM_CONFIG_UPDATE_NOTIFIER=false"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NODE_PATH=/opt/nodejs/node-v24.13.1/lib/node_modules"
      - "NODE_ENV=production"
      - "N8N_RELEASE_TYPE=stable"
      - "SHELL=/bin/sh"

    hostname: "bab69826894c"

    image: "docker.n8n.io/n8nio/n8n"

    ipc: "private"

    labels:
      com.docker.dhi.chain-id: "sha256:944769358dd7f77ef0ea2ae34d07317f84e07d5449adfdb9f763ac479326f348"
      com.docker.dhi.compliance: "cis"
      com.docker.dhi.created: "2026-02-20T09:02:53Z"
      com.docker.dhi.date.end-of-life: "2028-04-30"
      com.docker.dhi.date.release: "2025-05-06"
      com.docker.dhi.definition: "image/node/alpine-3.22/24-dev"
      com.docker.dhi.distro: "alpine-3.22"
      com.docker.dhi.flavor: ""
      com.docker.dhi.name: "dhi/node"
      com.docker.dhi.package-manager: "apk"
      com.docker.dhi.shell: "busybox"
      com.docker.dhi.title: "Node.js 24.x (dev)"
      com.docker.dhi.url: "https://dhi.io/catalog/node"
      com.docker.dhi.variant: "dev"
      com.docker.dhi.version: "24.13.1-alpine3.22-dev"
      org.opencontainers.image.description: "Workflow Automation Tool"
      org.opencontainers.image.source: "https://github.com/n8n-io/n8n"
      org.opencontainers.image.title: "n8n"
      org.opencontainers.image.url: "https://n8n.io"
      org.opencontainers.image.version: "2.12.2"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "22:d3:fb:0b:5c:5f"

    network_mode: "bridge"

    ports:
      - "5678:5678/tcp"

    user: "node"

    volumes:
      - "/home/ran-markovich/n8n_data:/home/node/.n8n"

    working_dir: "/home/node"

  nginx-proxy-manager:

    container_name: "nginx-proxy-manager"

    entrypoint:
      - "/init"

    environment:
      - "PATH=/opt/certbot/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt"
      - "OPENRESTY_VERSION=1.27.1.2"
      - "CROWDSEC_OPENRESTY_BOUNCER_VERSION=0.1.7"
      - "CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt"
      - "SUPPRESS_NO_CONFIG_WARNING=1"
      - "S6_BEHAVIOUR_IF_STAGE2_FAILS=1"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_FIX_ATTRS_HIDDEN=1"
      - "S6_KILL_FINISH_MAXTIME=10000"
      - "S6_VERBOSITY=1"
      - "NODE_ENV=production"
      - "NPM_BUILD_VERSION=2.14.0"
      - "NPM_BUILD_COMMIT=84fb2729"
      - "NPM_BUILD_DATE=2026-02-17 05:42:59 UTC"
      - "NODE_OPTIONS=--openssl-legacy-provider"

    hostname: "ff2369aff49c"

    image: "jc21/nginx-proxy-manager:latest"

    ipc: "private"

    labels:
      maintainer: "Jamie Curnow <jc@jc21.com>"
      org.label-schema.cmd: "docker run --rm -ti jc21/nginx-proxy-manager:latest"
      org.label-schema.description: "Docker container for managing Nginx proxy hosts with a simple, powerful\
        \ interface "
      org.label-schema.license: "MIT"
      org.label-schema.name: "nginx-proxy-manager"
      org.label-schema.schema-version: "1.0"
      org.label-schema.url: "https://github.com/jc21/nginx-proxy-manager"
      org.label-schema.vcs-url: "https://github.com/jc21/nginx-proxy-manager.git"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "82:48:9d:d3:1a:10"

    network_mode: "bridge"

    ports:
      - "443:443/tcp"
      - "80:80/tcp"
      - "81:81/tcp"

    restart: "unless-stopped"

    volumes:
      - "/home/ran-markovich/npm/data:/data"
      - "/home/ran-markovich/npm/letsencrypt:/etc/letsencrypt"

    working_dir: "/app"

  waha:

    command:
      - "/entrypoint.sh"

    container_name: "waha"

    entrypoint:
      - "/usr/bin/tini"
      - "--"

    environment:
      - "WHATSAPP_DEFAULT_ENGINE=WEBJS"
      - "WAHA_API_KEY=123456"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NODE_VERSION=24.11.1"
      - "YARN_VERSION=1.22.22"
      - "PUPPETEER_SKIP_DOWNLOAD=True"
      - "NODE_OPTIONS=--max-old-space-size=16384"
      - "WAHA_GOWS_PATH=/app/gows"
      - "WAHA_GOWS_SOCKET=/tmp/gows.sock"
      - "CHOKIDAR_USEPOLLING=1"
      - "CHOKIDAR_INTERVAL=5000"
      - "WAHA_ZIPPER=ZIPUNZIP"
      - "GODEBUG=netdns=cgo"

    hostname: "41a34a486b2e"

    image: "devlikeapro/waha"

    ipc: "private"

    labels:
      org.opencontainers.image.created: "2026-02-02T07:36:59.043Z"
      org.opencontainers.image.description: "WAHA - WhatsApp HTTP API (REST API) that you can configure\
        \ in a click! 3 engines: WEBJS (browser based), NOWEB (websocket nodejs), GOWS (websocket go)"
      org.opencontainers.image.licenses: "Apache-2.0"
      org.opencontainers.image.revision: "52222a6b9823e6984add3303b577292994402742"
      org.opencontainers.image.source: "https://github.com/devlikeapro/waha"
      org.opencontainers.image.title: "waha"
      org.opencontainers.image.url: "https://github.com/devlikeapro/waha"
      org.opencontainers.image.version: "latest"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "ce:a7:be:ca:75:79"

    network_mode: "bridge"

    ports:
      - "3000:3000/tcp"

    restart: "unless-stopped"

    volumes:
      - "/home/ran-markovich/.waha_sessions:/app/.sessions"

    working_dir: "/app"

version: "3.6"
