version: "3.6"
services:
  container_name: "nginx-proxy-manager"
  image: "jc21/nginx-proxy-manager:latest"
  ports:
     - "443:443/tcp"
     - "80:80/tcp"
     - "81:81/tcp"
  restart: "unless-stopped"
  volumes:
     - "${HOME}/npm/data:/data"
     - "${HOME}/npm/letsencrypt:/etc/letsencrypt"
